
services:
  backend:
    build: ./project_managing
    command: >
      sh -c "
            python manage.py collectstatic --noinput &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            gunicorn -c gunicorn.py project_managing.wsgi"

    container_name: backend
    user: "1000:1000"
    restart: always
    env_file:
      - .env
    links:
      - "postgres:db"
    volumes:
      - ./project_managing:/app
      - ./staticfiles:/app/staticfiles
    networks:
      - dbnet
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - dbnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    links:
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres
  
  redis:
    image: redis:8.0-alpine
    container_name: redis_db
    networks:
      - dbnet
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis_monitoring:
    image: redis/redisinsight:3.0
    container_name: redis_monitoring
    restart: always
    ports:
      - "5540:5540"
    environment:
      - REDISINSIGHT_REDIS_URLS=redis://:${REDIS_PASSWORD}@redis:6379
    networks:
      - dbnet
    depends_on:
      - redis

  celery:
    build: ./project_managing
    container_name: celery
    restart: always
    env_file:
      - .env
    command: celery -A project_managing worker --loglevel=info
    volumes:
      - ./project_managing:/app
    networks:
      - dbnet
    links:
      - "postgres:db"
      - "redis:redis"
    depends_on:
      - redis
      - postgres

  flower:
    build: ./project_managing
    container_name: flower
    restart: always
    env_file:
      - .env
    command: >
      celery -A project_managing flower 
      --port=5555 
      --broker=redis://:${REDIS_PASSWORD}@redis:6379/0
      --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}
    ports:
      - "5555:5555"
    networks:
      - dbnet
    depends_on:
      - redis
      - celery

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    networks:
      - dbnet
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    ports:
      - "80:8088"
    depends_on:
      - backend


volumes:
  postgres-data:
  redis-data:


networks:
  dbnet:
    driver: bridge
